# Generated by Django 2.1.7 on 2019-02-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlepagegalleryimage'),
    ]

    operations = [
    ]
