# Generated by Django 2.1.7 on 2019-02-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190222_0721'),
    ]

    operations = [
    ]
