# Generated by Django 2.1.8 on 2019-05-23 11:42

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('cover', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('image_position', wagtail.core.blocks.ChoiceBlock(choices=[('left top', 'Left Top'), ('left center', 'Left Center'), ('left bottom', 'Left Bottom'), ('right top', 'Right Top'), ('right center', 'Right Center'), ('right bottom', 'Right Bottom'), ('center top', 'Center Top'), ('center center', 'Center Center'), ('center bottom', 'Center Bottom')], icon='edit', required=False)), ('image_size', wagtail.core.blocks.ChoiceBlock(choices=[('cover', 'Full Cover'), ('half', 'Half')], icon='edit', required=False)), ('background_colour', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock()), ('text_align', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], icon='edit'))])), ('text_section', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('image_position', wagtail.core.blocks.ChoiceBlock(choices=[('left top', 'Left Top'), ('left center', 'Left Center'), ('left bottom', 'Left Bottom'), ('right top', 'Right Top'), ('right center', 'Right Center'), ('right bottom', 'Right Bottom'), ('center top', 'Center Top'), ('center center', 'Center Center'), ('center bottom', 'Center Bottom')], icon='edit', required=False)), ('image_display', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right'), ('background', 'Background')], icon='edit', required=False)), ('background_colour', wagtail.core.blocks.CharBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock()), ('text_align', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], icon='edit'))])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('card', wagtail.core.blocks.StreamBlock([('card', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('description', wagtail.core.blocks.RichTextBlock()), ('text_align', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], icon='edit'))]))])), ('carousel', wagtail.core.blocks.StreamBlock([('image', wagtail.core.blocks.StructBlock([('photo', wagtail.images.blocks.ImageChooserBlock()), ('caption_header', wagtail.core.blocks.CharBlock(required=False)), ('caption_text', wagtail.core.blocks.TextBlock(required=False))])), ('video', wagtail.embeds.blocks.EmbedBlock())], block_counts={'video': {'max_num': 2}}, max_num=10))], null=True),
        ),
    ]
