# Generated by Django 2.1.7 on 2019-03-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=500, verbose_name='Type')),
                ('value', models.CharField(max_length=500, verbose_name='Value')),
            ],
        ),
    ]
